"""Add persona_blueprints and prospect_personas tables

Revision ID: 06b0a80c8340
Revises: 
Create Date: 2025-12-26 11:13:57.922522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06b0a80c8340'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persona_blueprints',
    sa.Column('blueprint_id', sa.String(length=36), nullable=False),
    sa.Column('persona_type', sa.String(length=100), nullable=False),
    sa.Column('openers', sa.JSON(), nullable=True),
    sa.Column('value_angles', sa.JSON(), nullable=True),
    sa.Column('ctas', sa.JSON(), nullable=True),
    sa.Column('proof_points', sa.JSON(), nullable=True),
    sa.Column('tone_rules', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('blueprint_id'),
    sa.UniqueConstraint('persona_type'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('prospect_personas',
    sa.Column('persona_id', sa.String(length=36), nullable=False),
    sa.Column('prospect_id', sa.String(length=36), nullable=False),
    sa.Column('blueprint_id', sa.String(length=36), nullable=True),
    sa.Column('persona_type', sa.String(length=100), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('classification_method', sa.String(length=50), nullable=True),
    sa.Column('inferred_pain_points', sa.JSON(), nullable=True),
    sa.Column('classified_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['blueprint_id'], ['persona_blueprints.blueprint_id'], ),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.prospect_id'], ),
    sa.PrimaryKeyConstraint('persona_id'),
    sa.UniqueConstraint('prospect_id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prospect_personas')
    op.drop_table('persona_blueprints')
    # ### end Alembic commands ###
