"""Add suppression_expires_at to GlobalUnsubscribe

Revision ID: 3a896eb84020
Revises: add_suppression_expires_at
Create Date: 2026-02-26 12:59:46.202711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3a896eb84020'
down_revision: Union[str, Sequence[str], None] = 'add_suppression_expires_at'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reputation_alerts')
    op.drop_table('domain_health_snapshots')
    op.drop_table('sending_domains')
    op.alter_column('campaigns', 'campaign_timezone',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=True)
    op.drop_column('campaigns', 'enable_persona_rule')
    op.drop_column('campaigns', 'rotation_strategy')
    op.drop_index(op.f('idx_event_type'), table_name='email_events')
    op.drop_index(op.f('idx_message_event'), table_name='email_events')
    op.drop_index(op.f('idx_message_id'), table_name='email_events')
    op.drop_index(op.f('idx_campaign_id'), table_name='email_messages')
    op.drop_index(op.f('idx_campaign_status'), table_name='email_messages')
    op.drop_index(op.f('idx_status'), table_name='email_messages')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_status'), 'email_messages', ['status'], unique=False)
    op.create_index(op.f('idx_campaign_status'), 'email_messages', ['campaign_id', 'status'], unique=False)
    op.create_index(op.f('idx_campaign_id'), 'email_messages', ['campaign_id'], unique=False)
    op.create_index(op.f('idx_message_id'), 'email_events', ['message_id'], unique=False)
    op.create_index(op.f('idx_message_event'), 'email_events', ['message_id', 'event_type'], unique=False)
    op.create_index(op.f('idx_event_type'), 'email_events', ['event_type'], unique=False)
    op.add_column('campaigns', sa.Column('rotation_strategy', mysql.VARCHAR(length=50), server_default=sa.text("'STICKY'"), nullable=True))
    op.add_column('campaigns', sa.Column('enable_persona_rule', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True))
    op.alter_column('campaigns', 'campaign_timezone',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               nullable=False)
    op.create_table('sending_domains',
        sa.Column('domain_name', mysql.VARCHAR(length=255), nullable=False),
        sa.Column('spf_status', mysql.VARCHAR(length=50), nullable=True),
        sa.Column('dkim_status', mysql.VARCHAR(length=50), nullable=True),
        sa.Column('dmarc_status', mysql.VARCHAR(length=50), nullable=True),
        sa.Column('current_reputation_score', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('safety_threshold', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('is_blacklisted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
        sa.Column('warmup_status', mysql.VARCHAR(length=50), nullable=True),
        sa.Column('ses_reputation_status', mysql.VARCHAR(length=50), nullable=True),
        sa.Column('sesv2_enabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
        sa.Column('account_reputation_score', mysql.FLOAT(), nullable=True),
        sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('(now())'), nullable=True),
        sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('(now())'), nullable=True),
        sa.PrimaryKeyConstraint('domain_name'),
        mysql_collate='utf8mb4_0900_ai_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )
    op.create_table('domain_health_snapshots',
        sa.Column('snapshot_id', mysql.VARCHAR(length=36), nullable=False),
        sa.Column('domain_name', mysql.VARCHAR(length=255), nullable=False),
        sa.Column('snapshot_at', mysql.TIMESTAMP(), server_default=sa.text('(now())'), nullable=True),
        sa.Column('reputation_score', mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('bounce_rate_24h', mysql.FLOAT(), nullable=True),
        sa.Column('complaint_rate_24h', mysql.FLOAT(), nullable=True),
        sa.Column('open_rate_24h', mysql.FLOAT(), nullable=True),
        sa.Column('raw_metrics', mysql.JSON(), nullable=True),
        sa.ForeignKeyConstraint(['domain_name'], ['sending_domains.domain_name'], name=op.f('domain_health_snapshots_ibfk_1')),
        sa.PrimaryKeyConstraint('snapshot_id'),
        mysql_collate='utf8mb4_0900_ai_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )
    op.create_table('reputation_alerts',
        sa.Column('alert_id', mysql.VARCHAR(length=36), nullable=False),
        sa.Column('domain_name', mysql.VARCHAR(length=255), nullable=False),
        sa.Column('alert_type', mysql.VARCHAR(length=50), nullable=False),
        sa.Column('severity', mysql.VARCHAR(length=20), nullable=True),
        sa.Column('details', mysql.TEXT(), nullable=True),
        sa.Column('is_resolved', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
        sa.Column('resolution_notes', mysql.TEXT(), nullable=True),
        sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('(now())'), nullable=True),
        sa.Column('resolved_at', mysql.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(['domain_name'], ['sending_domains.domain_name'], name=op.f('reputation_alerts_ibfk_1')),
        sa.PrimaryKeyConstraint('alert_id'),
        mysql_collate='utf8mb4_0900_ai_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
