"""Add AI email fields and ComplianceCheck model

Revision ID: 614634adcede
Revises: 06b0a80c8340
Create Date: 2025-12-26 12:35:18.322899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '614634adcede'
down_revision: Union[str, Sequence[str], None] = '06b0a80c8340'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_checks',
    sa.Column('check_id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('spam_score', sa.Float(), nullable=True),
    sa.Column('spam_triggers_found', sa.JSON(), nullable=True),
    sa.Column('has_unsubscribe_link', sa.Boolean(), nullable=True),
    sa.Column('has_physical_address', sa.Boolean(), nullable=True),
    sa.Column('has_disallowed_phrases', sa.Boolean(), nullable=True),
    sa.Column('disallowed_phrases_found', sa.JSON(), nullable=True),
    sa.Column('contains_personal_data', sa.Boolean(), nullable=True),
    sa.Column('personal_data_types', sa.JSON(), nullable=True),
    sa.Column('gdpr_compliant', sa.Boolean(), nullable=True),
    sa.Column('can_spam_compliant', sa.Boolean(), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('failure_reasons', sa.JSON(), nullable=True),
    sa.Column('checked_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('checked_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['email_templates.template_id'], ),
    sa.PrimaryKeyConstraint('check_id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.add_column('email_messages', sa.Column('template_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'email_messages', 'email_templates', ['template_id'], ['template_id'])
    op.add_column('email_templates', sa.Column('model_settings', sa.JSON(), nullable=True))
    op.add_column('email_templates', sa.Column('generated_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('email_templates', sa.Column('cta_text', sa.String(length=255), nullable=True))
    op.add_column('email_templates', sa.Column('personalization_tokens', sa.JSON(), nullable=True))
    op.add_column('email_templates', sa.Column('expires_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_templates', 'expires_at')
    op.drop_column('email_templates', 'personalization_tokens')
    op.drop_column('email_templates', 'cta_text')
    op.drop_column('email_templates', 'generated_at')
    op.drop_column('email_templates', 'model_settings')
    op.drop_constraint(None, 'email_messages', type_='foreignkey')
    op.drop_column('email_messages', 'template_id')
    op.drop_table('compliance_checks')
    # ### end Alembic commands ###
