"""sync_schema_add_warmup

Revision ID: f3ae336735ba
Revises: 7a1d3f4b5c6e
Create Date: 2026-02-14 12:02:21.198171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f3ae336735ba'
down_revision: Union[str, Sequence[str], None] = '7a1d3f4b5c6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Cleaned up to only include relevant changes for email deliverability
    op.add_column('sending_inboxes', sa.Column('warmup_enabled', sa.Boolean(), nullable=True))
    op.add_column('sending_inboxes', sa.Column('warmup_day', sa.Integer(), nullable=True))
    op.add_column('sending_inboxes', sa.Column('warmup_start_date', sa.TIMESTAMP(), nullable=True))
    op.add_column('sending_inboxes', sa.Column('max_emails_per_day', sa.Integer(), nullable=True))
    op.add_column('sending_inboxes', sa.Column('delay_between_emails', sa.Integer(), nullable=True))
    op.add_column('sending_inboxes', sa.Column('emails_sent_today', sa.Integer(), nullable=True))
    op.add_column('sending_inboxes', sa.Column('last_daily_reset', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sending_inboxes', 'last_daily_reset')
    op.drop_column('sending_inboxes', 'emails_sent_today')
    op.drop_column('sending_inboxes', 'delay_between_emails')
    op.drop_column('sending_inboxes', 'max_emails_per_day')
    op.drop_column('sending_inboxes', 'warmup_start_date')
    op.drop_column('sending_inboxes', 'warmup_day')
    op.drop_column('sending_inboxes', 'warmup_enabled')
    # ### end Alembic commands ###
