"""add campaign_timezone

Revision ID: f915baccf877
Revises: f3ae336735ba
Create Date: 2026-02-19 13:16:23.081029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f915baccf877'
down_revision: Union[str, Sequence[str], None] = 'f3ae336735ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reputation_alerts')
    op.drop_table('sending_domains')
    op.drop_table('domain_health_snapshots')
    op.create_index(op.f('ix_campaign_drafts_tenant_id'), 'campaign_drafts', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_campaign_drafts_user_id'), 'campaign_drafts', ['user_id'], unique=False)
    op.drop_constraint(op.f('campaign_drafts_ibfk_1'), 'campaign_drafts', type_='foreignkey')
    op.drop_constraint(op.f('campaign_drafts_ibfk_2'), 'campaign_drafts', type_='foreignkey')
    op.drop_constraint(op.f('campaign_drafts_ibfk_3'), 'campaign_drafts', type_='foreignkey')
    op.drop_column('campaign_drafts', 'expires_at')
    op.drop_column('campaign_drafts', 'campaign_id')
    op.drop_index(op.f('idx_campaign'), table_name='campaign_inboxes')
    op.drop_constraint(op.f('fk_cp_last_inbox'), 'campaign_prospects', type_='foreignkey')
    op.drop_column('campaign_prospects', 'last_inbox_id')
    
    # Check if column exists first (safer approach for manual migrations)
    # Adding campaign_timezone
    op.add_column('campaigns', sa.Column('campaign_timezone', sa.String(length=100), default="UTC"))
    
    op.drop_constraint(op.f('fk_campaign_inbox'), 'campaigns', type_='foreignkey')
    op.drop_column('campaigns', 'rotation_strategy')
    op.drop_column('campaigns', 'inbox_id')
    op.drop_column('campaigns', 'enable_persona_rule')
    op.drop_index(op.f('idx_event_type'), table_name='email_events')
    op.drop_index(op.f('idx_message_event'), table_name='email_events')
    op.drop_index(op.f('idx_message_id'), table_name='email_events')
    op.drop_index(op.f('idx_campaign_id'), table_name='email_messages')
    op.drop_index(op.f('idx_campaign_status'), table_name='email_messages')
    op.drop_index(op.f('idx_status'), table_name='email_messages')
    op.create_foreign_key(None, 'email_messages', 'conversations', ['conversation_id'], ['id'])
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'email_messages', type_='foreignkey')
    op.create_index(op.f('idx_status'), 'email_messages', ['status'], unique=False)
    op.create_index(op.f('idx_campaign_status'), 'email_messages', ['campaign_id', 'status'], unique=False)
    op.create_index(op.f('idx_campaign_id'), 'email_messages', ['campaign_id'], unique=False)
    op.create_index(op.f('idx_message_id'), 'email_events', ['message_id'], unique=False)
    op.create_index(op.f('idx_message_event'), 'email_events', ['message_id', 'event_type'], unique=False)
    op.create_index(op.f('idx_event_type'), 'email_events', ['event_type'], unique=False)
    op.add_column('campaigns', sa.Column('enable_persona_rule', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True))
    op.add_column('campaigns', sa.Column('inbox_id', mysql.VARCHAR(length=36), nullable=True))
    op.add_column('campaigns', sa.Column('rotation_strategy', mysql.VARCHAR(length=50), server_default=sa.text("'STICKY'"), nullable=True))
    op.create_foreign_key(op.f('fk_campaign_inbox'), 'campaigns', 'sending_inboxes', ['inbox_id'], ['inbox_id'])
    op.drop_column('campaigns', 'campaign_timezone')
    op.add_column('campaign_prospects', sa.Column('last_inbox_id', mysql.VARCHAR(length=36), nullable=True))
    op.create_foreign_key(op.f('fk_cp_last_inbox'), 'campaign_prospects', 'sending_inboxes', ['last_inbox_id'], ['inbox_id'])
    op.create_index(op.f('idx_campaign'), 'campaign_inboxes', ['campaign_id'], unique=False)
    op.add_column('campaign_drafts', sa.Column('campaign_id', mysql.VARCHAR(length=36), nullable=True))
    op.add_column('campaign_drafts', sa.Column('expires_at', mysql.DATETIME(), nullable=True))
    op.create_foreign_key(op.f('campaign_drafts_ibfk_3'), 'campaign_drafts', 'campaigns', ['campaign_id'], ['campaign_id'])
    op.create_foreign_key(op.f('campaign_drafts_ibfk_2'), 'campaign_drafts', 'users', ['user_id'], ['user_id'])
    op.create_foreign_key(op.f('campaign_drafts_ibfk_1'), 'campaign_drafts', 'tenants', ['tenant_id'], ['tenant_id'])
    op.drop_index(op.f('ix_campaign_drafts_user_id'), table_name='campaign_drafts')
    op.drop_index(op.f('ix_campaign_drafts_tenant_id'), table_name='campaign_drafts')
    op.create_table('domain_health_snapshots',
        sa.Column('snapshot_id', mysql.VARCHAR(length=36), nullable=False),
        sa.Column('domain_name', mysql.VARCHAR(length=255), nullable=False),
        sa.Column('snapshot_at', mysql.TIMESTAMP(), server_default=sa.text('(now())'), nullable=True),
        sa.Column('reputation_score', mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('bounce_rate_24h', mysql.FLOAT(), nullable=True),
        sa.Column('complaint_rate_24h', mysql.FLOAT(), nullable=True),
        sa.Column('open_rate_24h', mysql.FLOAT(), nullable=True),
        sa.Column('raw_metrics', mysql.JSON(), nullable=True),
        sa.ForeignKeyConstraint(['domain_name'], ['sending_domains.domain_name'], name=op.f('domain_health_snapshots_ibfk_1')),
        sa.PrimaryKeyConstraint('snapshot_id'),
        mysql_collate='utf8mb4_0900_ai_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )
    op.create_table('sending_domains',
        sa.Column('domain_name', mysql.VARCHAR(length=255), nullable=False),
        sa.Column('spf_status', mysql.VARCHAR(length=50), nullable=True),
        sa.Column('dkim_status', mysql.VARCHAR(length=50), nullable=True),
        sa.Column('dmarc_status', mysql.VARCHAR(length=50), nullable=True),
        sa.Column('current_reputation_score', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('safety_threshold', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('is_blacklisted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
        sa.Column('warmup_status', mysql.VARCHAR(length=50), nullable=True),
        sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('(now())'), nullable=True),
        sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('(now())'), nullable=True),
        sa.Column('ses_reputation_status', mysql.VARCHAR(length=50), server_default=sa.text("'HEALTHY'"), nullable=True),
        sa.Column('sesv2_enabled', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
        sa.Column('account_reputation_score', mysql.FLOAT(), server_default=sa.text("'1'"), nullable=True),
        sa.PrimaryKeyConstraint('domain_name'),
        mysql_collate='utf8mb4_0900_ai_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )
    op.create_table('reputation_alerts',
        sa.Column('alert_id', mysql.VARCHAR(length=36), nullable=False),
        sa.Column('domain_name', mysql.VARCHAR(length=255), nullable=False),
        sa.Column('alert_type', mysql.VARCHAR(length=50), nullable=False),
        sa.Column('severity', mysql.VARCHAR(length=20), nullable=True),
        sa.Column('details', mysql.TEXT(), nullable=True),
        sa.Column('is_resolved', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
        sa.Column('resolution_notes', mysql.TEXT(), nullable=True),
        sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('(now())'), nullable=True),
        sa.Column('resolved_at', mysql.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(['domain_name'], ['sending_domains.domain_name'], name=op.f('reputation_alerts_ibfk_1')),
        sa.PrimaryKeyConstraint('alert_id'),
        mysql_collate='utf8mb4_0900_ai_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
